# Generated by Django 5.2.17 on 2026-10-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='diagnosticcentre',
            name='unique_centre_name_per_city',
        ),
        migrations.AddConstraint(
            model_name='diagnosticcentre',
            constraint=models.UniqueConstraint(fields=('name', 'city', 'address'), name='unique_centre_per_address'),
        ),
    ]
